[package]
name = "dev"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.56"
array-init = "2.0.0"
clap = { version = "3.1.8", features = ["derive"] }
serde = { version = "1.0.136", features = ["derive"] }
ureq = "2.4.0"
glib-sys = "0.15.10"
