[package]
name = "dev"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.56"
clap = { version = "3.1.8", features = ["derive", "env"] }
dircpy = "0.3.9"
glib-sys = "0.15.10"
ron = "0.7.0"
serde = { version = "1.0.136", features = ["derive"] }
ureq = "2.4.0"
